sudo: false
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
branches:
  only:
  - master
  - /^greenkeeper/.*$/
cache:
  directories:
  - node_modules
install:
- yarn
script:
- yarn test
- yarn run coveralls

jobs:
  include:
    - stage: npm release
      node_js: "8"
      script:
        - echo "Deploying to npm ..."
        - yarn build
      before_deploy:
        - cd dist
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          branch: master
          tags: true

