sudo: false
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
branches:
  only:
  - master
  - /^greenkeeper/.*$/
cache:
  directories:
  - node_modules
before_install:
- yarn install
install:
- yarn
script:
- yarn test
- yarn run coveralls
