name: CI

on: [push, pull_request]

jobs:
  build:
    name: 'Build'

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-verion}}
      - run: yarn install
      - run: yarn test
        env:
          CI: true
      - run: yarn run coveralls
      - run: yarn build
